package com.minquiers.helloworld.model;

import javax.persistence.*;

@Table(name = "movie")
public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.id
     *
     * @mbg.generated Tue Oct 09 10:24:18 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.id
     *
     * @return the value of movie.id
     *
     * @mbg.generated Tue Oct 09 10:24:18 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.id
     *
     * @param id the value for movie.id
     *
     * @mbg.generated Tue Oct 09 10:24:18 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}